# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20161210_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
