# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Food',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='password',
            new_name='main_dish',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='username',
            new_name='side_dish',
        ),
    ]
